# Generated by Django 3.0.6 on 2020-05-30 12:39

from django.db import migrations
from datetime import datetime as dt


def create_initial_users(apps, schema_def):
    User = apps.get_model('userActivity', 'User')

    User(real_name='Ramesh Hegde', id='DJ001', tz='Asia/Kolkatta').save()
    User(real_name='Dinesh Hegde', id='DJ002', tz='America/Los Angeles').save()
    User(real_name='Umesh Hegde', id='DJ003', tz='Dubai').save()
    User(real_name='Ravish Hegde', id='DJ004', tz='Africa').save()
    User(real_name='Lokesh Hegde', id='DJ005', tz='Germany').save()

    ActivityPeriod = apps.get_model('userActivity', 'ActivityPeriod')

    ActivityPeriod('1', dt(2020, 5, 31, 10, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 11, 00).strftime("%b %d %Y %I:%M%p"), 'DJ001').save()
    ActivityPeriod('2', dt(2020, 5, 31, 11, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 12, 15).strftime("%b %d %Y %I:%M%p"), 'DJ001').save()
    ActivityPeriod('3', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ001').save()

    ActivityPeriod('4', dt(2020, 5, 31, 10, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 11, 00).strftime("%b %d %Y %I:%M%p"), 'DJ002').save()
    ActivityPeriod('5', dt(2020, 5, 31, 11, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 12, 15).strftime("%b %d %Y %I:%M%p"), 'DJ002').save()
    ActivityPeriod('6', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ002').save()

    ActivityPeriod('7', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ003').save()
    ActivityPeriod('8', dt(2020, 5, 31, 11, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 12, 15).strftime("%b %d %Y %I:%M%p"), 'DJ003').save()
    ActivityPeriod('9', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ003').save()

    ActivityPeriod('10', dt(2020, 5, 31, 10, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 11, 00).strftime("%b %d %Y %I:%M%p"), 'DJ004').save()
    ActivityPeriod('11', dt(2020, 5, 31, 11, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 12, 15).strftime("%b %d %Y %I:%M%p"), 'DJ004').save()
    ActivityPeriod('12', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ004').save()

    ActivityPeriod('13', dt(2020, 5, 31, 10, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 11, 00).strftime("%b %d %Y %I:%M%p"), 'DJ005').save()
    ActivityPeriod('14', dt(2020, 5, 31, 11, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 12, 15).strftime("%b %d %Y %I:%M%p"), 'DJ005').save()
    ActivityPeriod('15', dt(2020, 5, 31, 12, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 1, 00).strftime("%b %d %Y %I:%M%p"), 'DJ005').save()

    ActivityPeriod('16', dt(2020, 5, 31, 14, 15).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 17, 30).strftime("%b %d %Y %I:%M%p"), 'DJ001').save()
    ActivityPeriod('17', dt(2020, 5, 31, 15, 15).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 16, 30).strftime("%b %d %Y %I:%M%p"), 'DJ002').save()
    ActivityPeriod('18', dt(2020, 5, 31, 2, 15).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 5, 30).strftime("%b %d %Y %I:%M%p"), 'DJ003').save()

    ActivityPeriod('19', dt(2020, 5, 31, 13, 15).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 14, 30).strftime("%b %d %Y %I:%M%p"), 'DJ004').save()
    ActivityPeriod('20', dt(2020, 5, 31, 18, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 19, 30).strftime("%b %d %Y %I:%M%p"), 'DJ002').save()
    ActivityPeriod('21', dt(2020, 5, 31, 13, 30).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 18, 30).strftime("%b %d %Y %I:%M%p"), 'DJ005').save()
    ActivityPeriod('22', dt(2020, 5, 31, 19, 00).strftime("%b %d %Y %I:%M%p"), dt(2020, 5, 31, 21, 30).strftime("%b %d %Y %I:%M%p"), 'DJ001').save()


class Migration(migrations.Migration):
    dependencies = [
        ('userActivity', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_users),
    ]
